#!/usr/bin/env zsh
# KON ZSH configuration
export ZSH_DISABLE_COMPFIX=true
export ZSH="/root/.oh-my-zsh"
ZSH_THEME=""
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

# Git branch info en el prompt — en amarillo
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '%F{yellow} [%b]%f'
zstyle ':vcs_info:git:*' actionformats '%F{yellow} [%b|%a]%f'
precmd_functions+=(vcs_info)

# Prompt
PS1="%F{#FF3B3B}%B[%b%F{#FF3B3B}%n %F{#FF3B3B}✘%f%F{#FF3B3B} %m%F{#FF3B3B}%B]-%B[%b%F{white}%~%F{#FF3B3B}%B]%b\${vcs_info_msg_0_}
%F{#FF3B3B}%B\$%b%f "

# ls colors
LS_COLORS="di=38;2;255;200;80:fi=38;2;220;220;220:ex=38;2;255;180;60:ln=38;2;120;200;255:so=38;2;180;140;255:bd=38;2;255;120;120:cd=38;2;255;160;80"
export LS_COLORS

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'

# Aliases
alias ll='ls -lahF --color=auto'
alias la='ls -la --color=auto'
alias ls='ls --color=auto'

# cd sin argumentos va a /anvil
alias cd='cd_func() { if [[ $# -eq 0 ]]; then cd /anvil; else builtin cd "$@"; fi; }; cd_func'

# History
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY

# Autocomplete improvements
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
unsetopt FLOW_CONTROL

# Directorio por defecto al iniciar
cd /anvil 2>/dev/null
